version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@11.5
  shellcheck: circleci/shellcheck@3.1
  gh-cli: circleci/github-cli@2.2.0
  github-release: duffn/github-release@0.3.0

filters: &filters
  tags:
    only: /.*/
jobs:
  release:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - github-release/release

workflows:
  release:
    jobs:
      - release:
          filters:
            branches:
              only:
                - main
