description: >
  This command setups GH authentication
parameters:
  GH_HOSTNAME:
    type: string
    default: "github.com"
    description: Specify the hostname of the GitHub instance to authenticate with.
  GH_TOKEN:
    type: env_var_name
    default: "GITHUB_TOKEN"
    description: |
      Enter the name of the environment variable containing the GitHub Personal Access token to be used for authentication.
      It is recommended for CI processes that you create a "machine" user on GitHub.com with the needed permissions, rather than using your own.

steps:
  - run:
      environment:
        GH_TOKEN: <<parameters.token>>
        GH_HOSTNAME: <<parameters.hostname>>
      name: Configure GH CLI v<<parameters.version>>
      command: <<include(scripts/configure.sh)>>
